{% set version = "0.7" %}

package:
  name: docx2txt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/docx2txt/docx2txt-{{ version }}.tar.gz
  sha256: 335363e5eb827dde2838fae69f5032b9a5c00f311def4022c196424bce697f0f

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - docx2txt

  commands:
    - docx2txt -h

about:
  home: https://github.com/ankushshah89/python-docx2txt
  license: MIT
  # license_file: LICENSE.txt - no MANIFEST.in in source; see https://github.com/ankushshah89/python-docx2txt/pull/8
  license_family: MIT
  summary: 'A pure python-based utility to extract text and images from docx files.'
  dev_url: https://github.com/ankushshah89/python-docx2txt

extra:
  recipe-maintainers:
    - pmlandwehr
    - nikicc
