travis:
  secure:
    BINSTAR_TOKEN: YvLQkQKNvADHKUoEQwjAtbtxoTg1+AwyvmgfSb4J9F+GbQUOFByBGbhmb/fbeSkS/RmbaxL1YMegcnXmGYlqF4OY7sC5ZufDiLZbaa1TCjdWFgZd5uDonVShLrORCdUIrAZe7nTnpAPRPvj2zJzVkPpOotoTNmFccCYQF1ViXdt+LOIIIkHmkvok23tj7Fsi7IW+6or7qN1VrNrusOQGbUStfbTIhv2Vwtrkekcf5bnDjFH0RmJ7oCAf+Pnsh1BiKYKKIUyntJ4T9PJz+MLPD/wf19k7PdWW6J2IltZF7uJ/sAld/WRqV2KobvdRhSR2lh/utMGmVXVu/y8C+wHo2WKAFgsfrQRyF/SJWingsIvygDuplaAhysdS56NrWx7g0N0LEJBOkH/pnKpRM7VJq7y6uGe9IE84GwRIfiScLyfH5f6nKN32mpSPCU9eMfz85QLR6/OnbKQYEU8lOYwQkl0b8h4zjQU7QFXCaYa3AuIpCnV6RtjKAnZB87sOUahp+tnp2MRrcpLbHOXwkOhvnIKFELN394hWlkJZtPZaRRIEVLRrfWfx1XHbENrKpV/E74Jmjk4479tj0mrxwYpG2l0xuhu0kxIg8Tom7lDUbgzV1DcW4qhXw8GyVONtpGFZFEH8BVU6X/eb57f0k911Ygg5f1pb9rQlptVoeGZPzTk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
