travis:
  secure:
    BINSTAR_TOKEN: ccLuXqb3clBlgIQuUFZ7upoo5Ffbyy45xpjtUT8mVXd5zcxK1llzOPsCzGit9yiVXCSMdyr42euzdF9tSTnj29/RDfCtxmWSgOIIdJppZ4Fe2j6Q9JOml95ZZjf3kmxvVEjT3UMbLeCh8XA6diTUu1RURlTxjr4bvI0F7y6CXnYz1aOBPUBMFAcrrbm6HJt+CJd+BaFWqZgbz+AR+MwDs9xtO0PLdRo/CtECtvF+jgc8LdE1qvMeyYuKnA8+rQtHkwbVLUDWYfDlAw2lu+1UhNMLtwdfO8v2KBXflSu+yDwGM9AgTzP8++v0ZbtWK4qtLKI2rk0kEAlphTKONXi+MzKxoYw71/F40QSGiTMUQvNYH2M2Vx2NxIArg4hdLbEpXalpkL4iJ5H77WqGRG9HD7FLJ2DqyxMBzLajxOhBXg+G9blA9DPnrmmpL4wEcNVn2mw6dPp7GtdhHQ4oy2FmXfUlWn4XdhGTgvUuJsTWBJuFuCNLTTbODE+hOWdX/iVkCyjiV+1P19jbyI5X4X12dmcD1INJ7O7ZreXJTh7Sb5T7oX373DwK3G1dNw45ylWMV5g1ookJuz57mxtSB1wobnPlAxchQH6SdGA1lF32WOA6CbZIkw5rZqo9GE3yrC0VdwCSi16zkIDTYinTARZL2ynRnvGJkrbaoPHjpkFuUOc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
