travis:
  secure:
    BINSTAR_TOKEN: M8xOEt9nu3t9gjGllwySDYU94FP2uwHa0xTBxcelekYjvkqA3KX3I1zH7+EyHhQ2RKs5v7faR8maBuRFKZKNV8ZHT9D6EvJ7CqRw2EcYpvZicyPORapgPyzziLCYYTeS/HNdgazqG+1AkW2+J8cv+W/TUJK7WBn5gw3IohMxOAT9Y6Bdl3zdsUUPeB2ssU9+yeskv5IRyu/5xQ9HdEcG4UMDsIXW/17raB0+C1XfPJAKreTOFyZ1mDQiXrixnODDcdkDyHxJD8pwm1kgld+ycHaccTCxfbdtTSRU2ayXPkqtNELvKtRCt7xykWnS71TcFtUkaZgRvMfg8hff1L3/VS5QOCIZ0EtiD4nGEBTd+/rsddL5zstS+yWF2fN6bZtCmM5r3v+/AKyys9eyXzSuHMT20u6qveJa4fwbtM/eSeajNgkFph6bzmsV+Kdo6QcUd2chOZUIZq2H0WZC38tR8Fc2uQM30+aYUlLoCi5wgn1ESeB0p8iaTnDuDDLi8hV+KQ8DH79U/+dHNW48ZT94cAYrKMDU0EKA9B9QD53/G3gGxY+uEBDIwwJIML1+KcRcr4Qaro/XM1DIU72wwQfLX8PYL0h2E8M2uIrONGfK/LHr0LaSNzrsrFqdYWAW3/8+z5doEkKNkrDDwGmmldxjaKfqvCd14WvC3x56JVdU6dE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
