travis:
  secure:
    BINSTAR_TOKEN: FWtN7sRfRwC1dAfsabwypl0Lvqx6VTgErjjRl0FcU527DVuM43VMS4MgZ3zvVrcbnQJnLGiSDmS7co5Y0tou/b/nDe5GfFYbDrOzxa5vdbDe9IXzvPIT4yQRdut7RLhSo29mtQzHfFbPih0sCNS0SGi+T74HrZO/WSJaxqLLhhE4pBvNQABaCFR6+tDuL3qfZdBnCjrPg8HFZ80HRZ+f6Re5dX+eFHLjqxj3BGnEq9BWQawhU+n/40IUWQofXr1lvJ12tM1WFXxcDkLqjBF/RHB9qXPJFZWpg5N1iFZXgxwebRcNScME5vOyBWmr7/A/F2W1/JVUs4D46mp6VnZ5duvq6jS/olO7X8mRn2y+XO1JedhnnZkBScG/+GSsHPNCW+d+V9z0g7VwEV7xf3S3aAChymEyl3IMWrxkVfCuHOC+A0BDaezRLizh81GZq9II+gzG3vlj1f/IvVQzdAwIDazziVME3WPx3dovfgET2j2SLMpGLzd6DNsUv11pWjKveomdQPEBGe0PsesRqvtcpsjKCXfPDK92eW4w0QuWUy28QATfLQlnvBDGeQ+xzkpaLNM3JwYo8lEjWwW1QbCrorX5+3L6+xR1fk/hpgWmeQgc2JUXsY6KoI2RB7PGxEhZK/FElFiwrb0HEn8d7s5vVA/u4ylmacguMBQB8y+DVXg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
